### ISSUE TITLE
Suggestion: blacklist or whitelist stones an ore can have. 

### ISSUE THREAD

**Issue by Trinsdar** [GregTech-Intergalactical/AntimatterAPI#113]
Currently the only type of ore is overworld ones, with their various stone variations.

Also wtf is up with the lang of the ores? 
Sphalerite Stone Stone Ore just sounds weird, i suggest you drop the second stone, it's redundant, and mive the stone name in front, so for example it would be Black Granite Sphalerite Ore

**Comment by Rongmario** [comment]
Lang files haven't been worked on in a millennia, feel free to PR

**Comment by Vliro** [comment]
Lang files have in fact been worked on, but not polished! Look into en_US provider.

**Comment by Vliro** [comment]
Ore lang kinda fixed.

**Comment by Trinsdar** [comment]
I've recently realized that end and nether ore flags are completely unnecessary,  since ores can have the end or nether stone type as long as the stone exists
