### ISSUE TITLE
Vertical Multiblocks form only in one direction

### ISSUE THREAD

**Issue by Midius** [GregTech-Intergalactical/AntimatterAPI#172]
When building multi blocks (like EBF or Multismelter) the multi block only forms in one direction
![unknown](https://user-images.githubusercontent.com/1699477/124129553-2cf63700-da7e-11eb-80a2-a585dc47ca16.png)

Side-note: Turning the controller block with a wrench does invalidate the multi block, but turning it back in the right direction does not reform it. It only reforms if you again break and replace any block on the Structure

**Comment by Vliro** [comment]
Should no longer be an issue.
