### ISSUE TITLE
EnumMaps are a thing

### ISSUE THREAD

**Issue by Speiger** [GregTech-Intergalactical/AntimatterAPI#173]
https://github.com/GregTech-Intergalactical/AntimatterAPI/blob/dev/src/main/java/muramasa/antimatter/capability/CoverHandler.java#L42

My Library also contains Enum2ObjectMaps or Enum2ObjectLinkedMaps
which has a faster access time and also only creates a backing array of the enum itself.
Null values are not supported though which from what I saw.

Also if you iterate over a set/map I would suggest you use "Linked" versions since they are not iterating over empty values.
(Also Map sizes are always devided by 0.75 and rounded up to the next power of two)

**Comment by Rongmario** [comment]
Nah we're good thanks, no need for an extra library. When I get around to I'll be cleaning all the data structures up anyway. Cheerio.

**Comment by Vliro** [comment]
Trinsdar linked in your object collection but it was 20mb of jar size which is not something we need.

**Comment by Speiger** [comment]
besides that. You ignored the point i am making since my implementation is very close to fastutils just more complete.
Iterating over NonLinkedMaps is a bad idea and sizes are adjusted.
Even if you remove my lib thats fine, but seriously look into EnumMaps whenever you use enums as keys and null isn't a problem.

Also good that switching back and forth is easy.

**Comment by Vliro** [comment]
We do use EnumMaps when needed.
