### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Thepigcat76** [GregTech-Intergalactical/AntimatterAPI#190]
Again latest version of gt4r, tesseract, antimatter

https://paste.ee/p/0T6yZ

**Comment by Vliro** [comment]
im sure @Trinsdar gave jars that might have been built with gradlew build, rather than gradlew publish?

**Comment by Thepigcat76** [comment]
What does that mean?

**Comment by Trinsdar** [comment]
oh I know the issue
