### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by mightydanp** [GregTech-Intergalactical/AntimatterAPI#61]
Failed to create mod instance. ModID: antimatter, class muramasa.antimatter.Antimatter
java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft;
	at muramasa.antimatter.Antimatter.lambda$null$2(Antimatter.java:58) ~[?:0.0.1] {re:classloading}

**Comment by Rongmario** [comment]
Are you trying to run it or build with it as a dependency?

**Comment by mightydanp** [comment]
I run it in as an api and when i lunch mc it gives that error

**Comment by Muramasa-** [comment]
Not really sure what you're trying to do here. For an example of how to use Antimatter, look at the GregTech repo.
